/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarymanagementsystem;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author HP
 */
public class DisplayIssued extends javax.swing.JFrame {

    Connection con;
        Statement stmt;
        int k;
        String roll8;
    /**
     * Creates new form DisplayIssued
     */
    public DisplayIssued(int a, String roll) {
        initComponents();
        Connect c1=new Connect();
        con=c1.connectDB();
        setSize(850,600);
        k=a;
        roll8=roll;
        
        if(a==1)
        {
           showTable1();
           jTable2.setVisible(false);
           jLabel2.setVisible(false);
        }
        else
        {
            showTable0();
            jTable1.setVisible(false);
            jLabel1.setVisible(false);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Noto Serif", 1, 24)); // NOI18N
        jLabel1.setText("List of books issued by all students");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(260, 30, 460, 80);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(240, 320, 452, 240);

        jLabel2.setFont(new java.awt.Font("Noto Serif", 1, 24)); // NOI18N
        jLabel2.setText("List of books issued by you");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(310, 60, 350, 80);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(240, 160, 450, 50);

        jButton1.setText("back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(700, 530, 55, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        new Dashboard(k,roll8).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    void showTable0(){
        try
        {
            stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("Select * from student1 where s_roll='"+roll8+"'");
            String str[]={"Roll No.","Name","Class","Book","Author","Publisher","DOI","DOR"};
            Object ob[][]= new Object[1][8];
            while(rs.next())
            {
                for(int j=0;j<8;j++)
                {
                 ob[0][j]=rs.getString(j+1);
                }
                
                jTable2.setModel(new DefaultTableModel (ob,str));
            }
        }
        catch(SQLException e)
        {
            
        }
    }
    
    void showTable1(){
        
        try
        {

            stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("Select* From student1");
        String str[]={"Roll No.","Name","Class","Book","Author","Publisher","DOI","DOR"};
        Object ob[][] = new Object[100][8];
        int i = 0;
        while(rs.next())
        {
            for(int j = 0 ; j<8; j++)
            {
        ob[i][j]= rs.getString(j+1);
            }
            i++;

        jTable1.setModel(new DefaultTableModel(ob,str));
        }
        jScrollPane1.setViewportView(jTable1);

        }
         catch(Exception e)
         {

         }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DisplayIssued.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DisplayIssued.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DisplayIssued.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DisplayIssued.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DisplayIssued(1,null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
