/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarymanagementsystem;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author HP
 */
public class InsertBook extends javax.swing.JFrame {

    Connection con;
        Statement stmt;
        int e;
        String roll3;
        
    /**
     * Creates new form InsertBook
     */
    public InsertBook(int a, String roll) {
        initComponents();
        Connect c1=new Connect();
        con=c1.connectDB();
        setSize(950,700);
        e=a;
        roll3=roll;
        setSerial();
        showTable();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setText("S.No.");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 70, 100, 30);

        jLabel3.setText("Book Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 130, 100, 30);

        jLabel4.setText("Author Name");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 190, 100, 30);

        jLabel5.setText("Publisher");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 250, 100, 30);

        jLabel6.setText("No. of Copies");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 310, 100, 30);

        jButton1.setText("SAVE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(280, 370, 90, 30);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(160, 70, 60, 20);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(160, 130, 130, 20);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(160, 190, 130, 20);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(160, 250, 130, 20);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(160, 310, 70, 20);

        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(390, 370, 80, 30);

        jButton3.setText("Refresh");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(40, 370, 73, 23);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(420, 40, 452, 190);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void showTable(){
        
        try
        {

            stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("Select* From book");
        String str[]={"Book name","Author name","Publisher","Inserted copies","Available copies"};
        Object ob[][] = new Object[100][5];
        int i = 0;
        while(rs.next())
        {
            for(int j = 0 ; j<5; j++)
            {
        ob[i][j]= rs.getString(j+1);
            }
            i++;

        jTable1.setModel(new DefaultTableModel(ob,str));
        }
        jScrollPane1.setViewportView(jTable1);

        }
         catch(Exception e)
         {

         }
    }
    
    void setSerial(){
        int serial=1;
        try{
            
            stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("select * from book");
            while(rs.next())
            {
                serial++;
            }
            
        }
        catch(Exception e)
        {
            
        }
        jTextField1.setText(""+serial);
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        //setSerial();
        
        try{
            stmt = con.createStatement();
            int available = 0;
            
            available = available + Integer.parseInt(jTextField5.getText());
            ResultSet pq = stmt.executeQuery("select * from book where book_name='"+jTextField2.getText()+"'");
            if(pq.next())
            {
                available = available + Integer.parseInt(pq.getString(5));
                stmt.executeUpdate("Update book set av_copy = '"+available+"' where book_name='"+jTextField2.getText()+"'");
                JOptionPane.showMessageDialog(null,"Record Updated...");
            }
            
            else
            {
                  stmt.executeUpdate("insert into book (book_name, author, publish, no_copy, av_copy) values ('"+jTextField2.getText()+"', '"+jTextField3.getText()+"', '"+jTextField4.getText()+"', '"+jTextField5.getText()+"', '"+available+"')");
                  JOptionPane.showMessageDialog(null,"Record saved...");  
            }
            

            
        }
        catch(SQLException e)
        {

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        new Dashboard(1,roll3).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        setSerial();
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsertBook(1,null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
