/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarymanagementsystem;
import javax.swing.*;
import java.sql.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
/**
 *
 * @author HP
 */
public class ReturnBook extends javax.swing.JFrame {

    Connection con;
        Statement stmt;
        int g;
        String roll5;
    /**
     * Creates new form ReturnBook
     */
    public ReturnBook(int a, String roll) {
        initComponents();
        Connect c1=new Connect();
        con=c1.connectDB();
        setSize(1000,625);
        g=a;
        roll5=roll;
        setRoll();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField2 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel3.setText("Roll No.");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(110, 80, 100, 30);

        jLabel4.setText("Author Name");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(110, 290, 100, 30);

        jLabel5.setText("Date of  return");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(110, 440, 100, 30);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(240, 180, 130, 30);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(240, 290, 130, 30);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(240, 340, 130, 30);

        jLabel6.setText("Book Name");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(110, 240, 100, 30);

        jLabel8.setText("Class");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(110, 180, 100, 30);

        jLabel9.setText("Name");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(110, 130, 100, 30);

        jLabel10.setText("Publisher");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(110, 340, 100, 30);

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(240, 240, 130, 22);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(240, 130, 130, 30);
        getContentPane().add(jTextField6);
        jTextField6.setBounds(240, 390, 130, 30);

        jButton1.setText("DONE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(190, 500, 100, 30);

        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(240, 80, 130, 30);

        jLabel2.setText("Return Date");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(110, 400, 70, 14);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(240, 440, 130, 30);

        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(330, 500, 90, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    void setRoll(){
        try
        {
            stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("select distinct s_roll from student1");
            
            while(rs.next())
            {
                jComboBox2.addItem(rs.getString(1));
            }
        }
        catch(SQLException e)
        {
            
        }
    }
    
    void date()
        {
            try
        {

            stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("select* from student1 where s_roll = '"+jComboBox2.getSelectedItem().toString()+"' and book_name ='"+jComboBox1.getSelectedItem().toString()+"'"); 

            if(rs.next())
            {

              jTextField1.setText(rs.getString(8));

            }
        }
        catch(Exception e)
        {

        } 
        }

    
    void setFields(){
        
        try
        {
            stmt = con.createStatement();
          
          ResultSet pq = stmt.executeQuery("select * from book where book_name='"+jComboBox1.getSelectedItem().toString()+"'");
        
        if(pq.next())
        {
            jTextField4.setText(pq.getString(2));
            jTextField5.setText(pq.getString(3));
        }
        
        ResultSet rs = stmt.executeQuery("select * from student1 where s_roll='"+jComboBox2.getSelectedItem().toString()+"'");
        
        if(rs.next())
        {
            jTextField2.setText(rs.getString(2));
            jTextField3.setText(rs.getString(3));
        }
                
        jTextField6.setText(java.time.LocalDate.now().toString());
        }
        catch(SQLException e){
            
        }
        
        
    }
    
    void setBookName(){
        try
        {
            stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("select * from student1 where s_roll='"+jComboBox2.getSelectedItem().toString()+"'");
            
        while(rs.next())
        {
         jComboBox1.addItem(rs.getString(4));
        }
        }
        catch(SQLException e)
        {
            
        }
    }
    
    long difference(String start_date, String end_date){
        
       SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
       long difference_In_Days=0;
       try
       {
           Date d1 = sdf.parse(start_date);
           Date d2 = sdf.parse(end_date);
           
           long difference_In_Time = d2.getTime() - d1.getTime();
           difference_In_Days = (difference_In_Time / (1000 * 60 * 60 * 24))% 365;
           
       }
       catch(Exception e)
       {
           
       }
       return difference_In_Days;
    }
    
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        
        setFields();
        date();
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        try
        {
            stmt = con.createStatement();
            stmt.executeUpdate("delete from student1 where s_roll='"+jComboBox2.getSelectedItem().toString()+"' and book_name='"+jComboBox1.getSelectedItem().toString()+"'");
            JOptionPane.showMessageDialog(null, "Book successfully returned");
            
            ResultSet pq = stmt.executeQuery("select * from book where book_name='"+jComboBox1.getSelectedItem().toString()+"'");
            if(pq.next())
            {
                int av = Integer.parseInt(pq.getString(5))+1;
                stmt.executeUpdate("Update book set av_copy = '"+av+"' where book_name='"+jComboBox1.getSelectedItem().toString()+"'");
                JOptionPane.showMessageDialog(null,"Record Updated");
                
                
                
                String start = jTextField1.getText();
                String last = jTextField6.getText();
                long diff = difference(start,last);
                int fine;
                if(diff<0)
                {
                    fine=0;
                }
                else
                {
                   fine =(int)diff*20;
                }
                stmt.executeUpdate("insert into fine values('"+jComboBox2.getSelectedItem().toString()+"', '"+jTextField2.getText()+"', '"+jTextField3.getText()+"', '"+jComboBox1.getSelectedItem().toString()+"', '"+jTextField1.getText()+"', '"+jTextField6.getText()+"', '"+fine+"')");
                JOptionPane.showMessageDialog(null,"Fine table updated");
                
                
                
            }
            
            
            
        }
        catch(SQLException e)
        {
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        
       jComboBox1.removeAllItems();
        setBookName();
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        new Dashboard(1,roll5).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReturnBook(1,null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
