/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarymanagementsystem;


import java.sql.*;
import javax.swing.*;

/**
 *
 * @author HP
 */
public class SignUp extends javax.swing.JFrame {
    

    Connection con;
    Statement stmt;
    
    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
        Connect c1=new Connect();
        con=c1.connectDB();
        setSize(750,750);
    }
    
    void check(){
            
        String str = jTextField7.getText();
        String xyz = jTextField8.getText();

        char store;
        boolean flag1=false, flag2=true, flag3=false;
        int count = 0;

        for(int i=0; i<=str.length(); i++)
        {
            store = str.charAt(i);

            if(store == '@')
            {
                flag1 = true;
            }

            if(store == '.')
            {
                for(int j= i+1; j<=str.length()-1; j++)
                {
                    count++;
                }
                break;
            }
        }
        
        if(count >=2 && count <=3)
        {
            flag3 = true;
        }

        if(xyz.length()!=6)
        {
            flag2 = false;
        }
        
        if(flag1==true && flag3==true && flag2==true)
        {
            insert();
        }
        
        else
        {
            if((flag1==false || flag3==false) && flag2==false)
            {
                jTextField7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 153))));
                jTextField8.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 153))));
                JOptionPane.showMessageDialog(null, "Error signing. Kindly check email and password");
            }
            else if(flag1==false || flag3 == false)
            {
                jTextField7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 153))));
                JOptionPane.showMessageDialog(null, "Error signing. Kindly check your email");
            }
            else if(flag2==false)
            {
                jTextField8.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 153))));
                JOptionPane.showMessageDialog(null, "Error signing. Password should be exact 6 digits");
            }
        }
        
        
        
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setText("Address");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 390, 60, 30);

        jLabel2.setText("Roll Number");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 50, 70, 30);

        jLabel3.setText("First Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 100, 60, 30);

        jLabel4.setText("Last Name");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 150, 70, 30);

        jLabel5.setText("Class");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 200, 50, 30);

        jLabel6.setText("Username");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 250, 60, 30);

        jLabel7.setText("Email ID");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 300, 60, 30);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(130, 400, 110, 20);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(130, 50, 110, 20);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(130, 100, 110, 20);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(130, 150, 110, 20);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(130, 200, 110, 20);

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField6);
        jTextField6.setBounds(130, 250, 110, 20);
        getContentPane().add(jTextField7);
        jTextField7.setBounds(130, 300, 110, 20);

        jLabel8.setText("Password");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 350, 60, 30);

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField8);
        jTextField8.setBounds(130, 350, 110, 20);

        jButton1.setText("cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(210, 470, 73, 23);

        jButton2.setText("submit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(70, 470, 80, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentHidden

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    void insert()
    {   
        int check=0;
        try
        {
            stmt = con.createStatement();
            
            ResultSet rs = stmt.executeQuery("Select * from lib where s_roll = '"+jTextField2.getText()+"'");
            
            while(rs.next())
            {
                if(jTextField6.getText().equals(rs.getString(5)))
                {
                    JOptionPane.showMessageDialog(null,"Username already taken by the user!");
                    check =1;
                }
            }
            
            if(check == 0)
            {
                stmt.executeUpdate("insert into lib (s_roll, f_name, l_name, class, user_id, email_id, s_pass, address) values ('"+jTextField2.getText()+"', '"+jTextField3.getText()+"', '"+jTextField4.getText()+"', '"+jTextField5.getText()+"', '"+jTextField6.getText()+"', '"+jTextField7.getText()+"' , '"+jTextField8.getText()+"', '"+jTextField1.getText()+"')"); 
                    JOptionPane.showMessageDialog(null,"Record saved...");
            }
            
           
        }
        catch(SQLException e)
        {
            //JOptionPane.showMessageDialog(null,"Enter all details first!");
        }
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        check();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Login(0).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
