/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarymanagementsystem;
import javax.swing.*;
import java.sql.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class Student extends javax.swing.JFrame {
    DefaultTableModel dtm;
    Connection con;
        Statement stmt;
        int f;
        String roll4;
    /**
     * Creates new form Student
     */
    public Student(int a, String roll) {
        initComponents();
        Connect c1=new Connect();
        con=c1.connectDB();
        setSize(875,750);
        f=a;
        roll4=roll;
        setBookName();
        showTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();

        jLabel7.setText("Class");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel3.setText("Roll No.");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(110, 80, 100, 30);

        jLabel4.setText("Author Name");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(110, 290, 100, 30);

        jLabel5.setText("Date of issue");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(110, 390, 100, 30);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(240, 180, 130, 30);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(240, 290, 130, 30);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(240, 340, 130, 30);

        jLabel6.setText("Book Name");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(110, 240, 100, 30);

        jLabel8.setText("Class");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(110, 180, 100, 30);

        jLabel9.setText("Name");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(110, 130, 100, 30);

        jLabel10.setText("Publisher");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(110, 340, 100, 30);

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(240, 240, 130, 22);

        jButton1.setText("SAVE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(200, 510, 100, 30);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(240, 80, 130, 30);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(240, 130, 130, 30);
        getContentPane().add(jTextField6);
        jTextField6.setBounds(240, 390, 130, 30);

        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(330, 510, 90, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "s_roll", "name", "class", "book_name", "author", "publish", "doi", "dor"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(380, 70, 440, 210);

        jButton3.setText("SHOW");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(550, 300, 100, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void setBookName(){
        
        try
        {
            stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("select distinct book_name from book");
            
        while(rs.next())
        {
         jComboBox1.addItem(rs.getString(1));
        }
        }
        catch(SQLException e)
        {
            
        }
    }
    
    void setFields(){
        
        try{
            stmt = con.createStatement();
          
          ResultSet pq = stmt.executeQuery("select * from book where book_name='"+jComboBox1.getSelectedItem().toString()+"'");
        
        if(pq.next())
        {
            jTextField4.setText(pq.getString(2));
            jTextField5.setText(pq.getString(3));
        }
        jTextField6.setText(""+java.time.LocalDate.now());
        }
        catch(SQLException e){
            
        }
        
        
    }
    
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        
        setFields();
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            
        stmt = con.createStatement();
        ResultSet pq = stmt.executeQuery("select * from book where book_name='"+jComboBox1.getSelectedItem().toString()+"'");
        
        if(pq.next())
            {
                int av = Integer.parseInt(pq.getString(5))-1;
                if(Integer.parseInt(pq.getString(5))==0)
                {
                    JOptionPane.showMessageDialog(null,"Book not available");
                }
                else
                {
                    ResultSet rs = stmt.executeQuery("select * from student1 where s_roll='"+jTextField1.getText()+"'");
                    int count=0;
                    boolean flag1=true, flag2=true;
                    while(rs.next())
                    {
                        count++;
                        if(rs.getString(4).equals(jComboBox1.getSelectedItem()))
                        {
                            flag2 = false;
                        }
                    }
                    
                    if(count>2)
                    {
                        flag1=false;
                    }
                    
                    if(flag1==true && flag2==true)
                    {
                        stmt.executeUpdate("insert into student1 values('"+jTextField1.getText()+"','"+jTextField2.getText()+"' ,'"+jTextField3.getText()+"','"+jComboBox1.getSelectedItem().toString()+"','"+jTextField4.getText()+"','"+jTextField5.getText()+"','"+jTextField6.getText()+"', '"+java.time.LocalDate.now().plusDays(15)+"')");
                        JOptionPane.showMessageDialog(null,"Record Saved.....");
                        stmt.executeUpdate("Update book set av_copy = '"+av+"' where book_name='"+jComboBox1.getSelectedItem().toString()+"'");
                        JOptionPane.showMessageDialog(null,"Record Updated");
                    }
                    
                    else if(flag1==false)
                    {
                        JOptionPane.showMessageDialog(null, "Can't issue more than 3 books!");
                    }
                    else if(flag2==false)
                    {
                        JOptionPane.showMessageDialog(null, "Book already issued!");
                    }
                    
                }
                
            }
        else
        {
            JOptionPane.showMessageDialog(null, "Book not available");
        }
        
        }
        catch(SQLException e)
        {
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        new Dashboard(1,roll4).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    void showTable(){
        
        try
        {

            stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("Select* From student1");
        String str[]={"Roll No","Name","Class","Book Name","Author","Publisher","DOI","DOR"};
        Object ob[][] = new Object[100][8];
        int i = 0;
        while(rs.next())
        {
            for(int j = 0 ; j<8; j++)
            {
        ob[i][j]= rs.getString(j+1);
            }
            i++;
            dtm=new DefaultTableModel(ob,str);
        jTable1.setModel(dtm);
        }
        jScrollPane1.setViewportView(jTable1);

        }
         catch(Exception e)
         {
// jTextField1.setText(ob[getSelectedRow(), 0].toString()
         }
    }
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
    
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        //int c=jTable1.getSelectedColumn();
        int r=jTable1.getSelectedRow();
        
        jTextField1.setText(""+dtm.getValueAt(r, 0));
        jTextField2.setText(""+dtm.getValueAt(r, 1));
        jTextField3.setText(""+dtm.getValueAt(r, 2));
        
    }//GEN-LAST:event_jTable1MouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student(1,null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
